Repository RUSH-1472/rush-logistic-system-2024, pull requests merged in 2024-12, with the labels that each got.

#1 [Feat/init server gateway] eureka server 와 gateway service 초기 세팅
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/rush-logistic-system-2024.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  com.rush.logistic.client.order-delivery/.gitattributes
  com.rush.logistic.client.order-delivery/.gitignore
  com.rush.logistic.client.order-delivery/build.gradle
  com.rush.logistic.client.order-delivery/gradle/wrapper/gradle-wrapper.jar
  com.rush.logistic.client.order-delivery/gradle/wrapper/gradle-wrapper.properties
  com.rush.logistic.client.order-delivery/gradlew
  com.rush.logistic.client.order-delivery/gradlew.bat
  com.rush.logistic.client.order-delivery/settings.gradle
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/OrderDeliveryApplication.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/checker/HealthCheckController.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/common/response/BaseResponse.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/common/response/BasicCode.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/common/response/OrderCode.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/common/response/StatusCode.java
  com.rush.logistic.client.order-delivery/src/main/resources/application.yml
  com.rush.logistic.client.order-delivery/src/test/java/com/rush/logistic/client/order_delivery/OrderDeliveryApplicationTests.java
  com.rush.logistic.gateway/.gitattributes
  com.rush.logistic.gateway/.gitignore
  com.rush.logistic.gateway/build.gradle
  com.rush.logistic.gateway/gradle/wrapper/gradle-wrapper.jar
  com.rush.logistic.gateway/gradle/wrapper/gradle-wrapper.properties
  com.rush.logistic.gateway/gradlew
  com.rush.logistic.gateway/gradlew.bat
  com.rush.logistic.gateway/settings.gradle
  com.rush.logistic.gateway/src/main/java/com/rush/logistic/gateway/EndpointConst.java
  com.rush.logistic.gateway/src/main/java/com/rush/logistic/gateway/GatewayApplication.java
  com.rush.logistic.gateway/src/main/java/com/rush/logistic/gateway/JwtAuthenticationFilter.java
  com.rush.logistic.gateway/src/main/resources/application.yml
  com.rush.logistic.gateway/src/test/java/com/rush/logistic/gateway/GatewayApplicationTests.java
  com.rush.logistic.server/.gitattributes
  com.rush.logistic.server/.gitignore
  com.rush.logistic.server/build.gradle
  com.rush.logistic.server/gradle/wrapper/gradle-wrapper.jar
  com.rush.logistic.server/gradle/wrapper/gradle-wrapper.properties
  com.rush.logistic.server/gradlew
  com.rush.logistic.server/gradlew.bat
  com.rush.logistic.server/settings.gradle
  com.rush.logistic.server/src/main/java/com/rush/logistic/server/ServerApplication.java
  com.rush.logistic.server/src/main/resources/application.yml
  com.rush.logistic.server/src/test/java/com/rush/logistic/server/ServerApplicationTests.java
Labels: enhancement

#6 [Feat/init auth] auth 프로젝트 생성
  com.rush.logistic.client.auth/.gitattributes
  com.rush.logistic.client.auth/.gitignore
  com.rush.logistic.client.auth/build.gradle
  com.rush.logistic.client.auth/gradle/wrapper/gradle-wrapper.jar
  com.rush.logistic.client.auth/gradle/wrapper/gradle-wrapper.properties
  com.rush.logistic.client.auth/gradlew
  com.rush.logistic.client.auth/gradlew.bat
  com.rush.logistic.client.auth/settings.gradle
  com.rush.logistic.client.auth/src/main/java/com/rush/logistic/client/auth/AuthApplication.java
  com.rush.logistic.client.auth/src/main/resources/application.properties
  com.rush.logistic.client.auth/src/test/java/com/rush/logistic/client/auth/AuthApplicationTests.java
Labels: enhancement

#8 [Feat/init company product] company-product 프로젝트 생성
  com.rush.logistic.client.company-product/.gitattributes
  com.rush.logistic.client.company-product/.gitignore
  com.rush.logistic.client.company-product/build.gradle
  com.rush.logistic.client.company-product/gradle/wrapper/gradle-wrapper.jar
  com.rush.logistic.client.company-product/gradle/wrapper/gradle-wrapper.properties
  com.rush.logistic.client.company-product/gradlew
  com.rush.logistic.client.company-product/gradlew.bat
  com.rush.logistic.client.company-product/settings.gradle
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/CompanyProductApplication.java
  com.rush.logistic.client.company-product/src/main/resources/application.properties
  com.rush.logistic.client.company-product/src/test/java/com/rush/logistic/client/company_product/CompanyProductApplicationTests.java
Labels: enhancement

#11 [Feat/hub detail api] 특정 HUB 조회 API 개발
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubInfoResponseDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#12 [Feat/hub update api] 특정 HUB 수정 API 개발
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/Hub.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#10 [Feat/auth api] auth 로그인, 로그아웃 API 개발
  com.rush.logistic.client.auth/build.gradle
  com.rush.logistic.client.auth/src/main/java/com/rush/logistic/client/auth/AuthConfig.java
  com.rush.logistic.client.auth/src/main/java/com/rush/logistic/client/auth/AuthController.java
  com.rush.logistic.client.auth/src/main/java/com/rush/logistic/client/auth/AuthService.java
  com.rush.logistic.client.auth/src/main/java/com/rush/logistic/client/auth/UserRepository.java
  com.rush.logistic.client.auth/src/main/java/com/rush/logistic/client/auth/core/domain/User.java
  com.rush.logistic.client.auth/src/main/resources/application.properties
  com.rush.logistic.client.auth/src/main/resources/application.yml
  com.rush.logistic.gateway/src/main/resources/application.yml
Labels: enhancement

#13 [Feat/company api] company 생성, 조회 API 개발
  com.rush.logistic.client.company-product/.gitignore
  com.rush.logistic.client.company-product/build.gradle
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/CompanyProductApplication.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/config/JpaConfig.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/controller/CompanyController.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/CompanyDto.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/request/CompanyCreateRequest.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/response/CompanySearchResponse.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/entity/BaseEntity.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/entity/Company.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/repository/CompanyRepository.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/service/CompanyService.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/type/CompanyType.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/ApplicationException.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/ErrorCode.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/ErrorResponse.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/GlobalExceptionHandler.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/Response.java
  com.rush.logistic.client.company-product/src/main/resources/application.properties
  com.rush.logistic.client.company-product/src/main/resources/application.yml
Labels: enhancement

#15 [Feat/hub delete api] 특정 HUB 삭제 API 개발
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/Hub.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#19 [Refactor/company api] companyId 출력, Errormessage 추가
  com.rush.logistic.client.company-product/build.gradle
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/controller/CompanyController.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/request/CompanyCreateRequest.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/service/CompanyService.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/ErrorCode.java
Labels: enhancement

#16 [Feat/hub findAll api] 전체 HUB 목록 조회 API 개발
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubListResponseDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#21 [Feat/product api] Product CRUD API 개발
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/controller/ProductController.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/ProductDto.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/request/ProductCreateRequest.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/request/ProductUpdateRequest.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/dto/response/ProductSearchResponse.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/entity/Product.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/repository/ProductRepository.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/service/ProductService.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/ErrorCode.java
Labels: enhancement

#20 [Feat/create order] Order 와 Delivery CRUD 구현
  .idea/gradle.xml
  .idea/modules.xml
  com.rush.logistic.client.order-delivery/build.gradle
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/checker/HealthCheckController.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/controller/DeliveryController.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/controller/dto/request/DeliveryAllReq.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/controller/dto/response/DeliveryAllRes.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/controller/dto/response/DeliveryIdRes.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/domain/Delivery.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/domain/DeliveryStatusEnum.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/exception/DeliveryCode.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/exception/DeliveryException.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/repository/DeliveryRepository.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery/service/DeliveryService.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/controller/OrderController.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/controller/dto/request/OrderAllReq.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/controller/dto/request/OrderAndDeliveryAllReq.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/controller/dto/response/OrderAllRes.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/controller/dto/response/OrderIdRes.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/domain/Order.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/exception/OrderCode.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/exception/OrderException.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/repository/OrderRepository.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/order/service/OrderService.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/common/BaseAudit.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/common/GlobalConst.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/common/response/BaseResponse.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/exception/BaseException.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/exception/GlobalExceptionHandler.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/response/BaseResponse.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/response/BasicCode.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/global/response/StatusCode.java
  com.rush.logistic.client.order-delivery/src/main/resources/application.yml
Labels: enhancement

#22 :bug: fix : update,delete bug fix
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/controller/CompanyController.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/service/CompanyService.java
Labels: enhancement

#26 [dev] 중복된 Hub Message 삭제
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
Labels: enhancement

#25 [Feat/hubs routes create api] HUB간 경로 정보 생성 API
  .idea/.gitignore
  com.rush.logistic.client.hub/.env
  com.rush.logistic.client.hub/.gitignore
  com.rush.logistic.client.hub/build.gradle
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/config/DotenvConfig.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubRouteController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubPointRequestDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubRouteIdResponseDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/LatLonDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/TimeTakenAndDistDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubRouteMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/HubRoute.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRouteRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubRouteService.java
  com.rush.logistic.client.hub/src/main/resources/application.yml
Labels: enhancement

#29 [feat/crud-delivery-route] delivery-route 임시 CRUD 구현
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/controller/DeliveryRouteController.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/controller/dto/request/DeliveryRouteCreateReq.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/controller/dto/request/DeliveryRouteUpdateReq.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/controller/dto/response/DeliveryRouteAllRes.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/controller/dto/response/DeliveryRouteIdRes.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/domain/DeliveryRoute.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/exception/DeliveryRouteCode.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/exception/DeliveryRouteException.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/repository/DeliveryRouteRepository.java
  com.rush.logistic.client.order-delivery/src/main/java/com/rush/logistic/client/order_delivery/domain/delivery_route/service/DeliveryRouteService.java
Labels: enhancement

#30 [Feat/hub route read api] HUB간 경로 조회 API 및 HUB 경로 조회 API 개발
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubRouteController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubRouteInfoResponseDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubRouteMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRouteRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubRouteService.java
Labels: enhancement

#38 [refactor] 사용하지 않는 AUTH Project 삭제
  com.rush.logistic.client.auth/.gradle/8.11.1/checksums/checksums.lock
  com.rush.logistic.client.auth/.gradle/8.11.1/checksums/md5-checksums.bin
  com.rush.logistic.client.auth/.gradle/8.11.1/checksums/sha1-checksums.bin
  com.rush.logistic.client.auth/.gradle/8.11.1/executionHistory/executionHistory.lock
  com.rush.logistic.client.auth/.gradle/8.11.1/fileChanges/last-build.bin
  com.rush.logistic.client.auth/.gradle/8.11.1/fileHashes/fileHashes.bin
  com.rush.logistic.client.auth/.gradle/8.11.1/fileHashes/fileHashes.lock
  com.rush.logistic.client.auth/.gradle/8.11.1/gc.properties
  com.rush.logistic.client.auth/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  com.rush.logistic.client.auth/.gradle/buildOutputCleanup/cache.properties
  com.rush.logistic.client.auth/.gradle/vcs-1/gc.properties
Labels: invalid

#32 [Refactor/company api] zipkin 추가, keyword or hubId 사용 검색
  com.rush.logistic.client.company-product/build.gradle
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/company/controller/CompanyController.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/company/repository/CompanyRepository.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/company/repository/CompanyRepositoryCustom.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/company/repository/CompanyRepositoryImpl.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/company/service/CompanyService.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/product/repository/ProductRepository.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/product/repository/ProductRepositoryCustom.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/product/repository/ProductRepositoryImpl.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/product/service/ProductService.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/ErrorCode.java
  com.rush.logistic.client.company-product/src/main/resources/application.yml
Labels: enhancement

#40 [Feat/slack api] Slack message update/delete API 개발
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/controller/SlackController.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/dto/SlackUpdateRequestDto.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/dto/SlackUpdateResponseDto.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/entity/SlackEntity.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/service/SlackService.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/user/service/UserService.java
Labels: enhancement

#41 [feat/hub-route-read-api] HUB간 경로 조회시 Hub route 고유 식별자 함께 제공
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubRouteInfoResponseDto.java
Labels: enhancement

#43 [Feat/hub route optimize api] HUB간 경로 조회 API 개발
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubRouteController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/EdgeDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubRouteListResponseDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubName.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/HubRoute.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRouteRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubRouteService.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#45 [Test/remove idea] .idea 관련 차일 삭제
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/rush-logistic-system-2024.iml
  com.rush.logistic.client.hub/build.gradle~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/config/DotenvConfig.java~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/config/DurationAttributeConverter.java~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/config/RestTemplateConfig.java~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubInfoResponseDto.java~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubListResponseDto.java~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubRouteInfoResponseDto.java~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/HubRoute.java~
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRouteRepository.java~
Labels: bug

#46 [Refactor/slack, User api] Slack ,User QueryDSL
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/controller/SlackController.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/dto/SlackInfoResponseDto.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/global/ApiResponse.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/repository/SlackRepositoryCustom.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/repository/SlackRepositoryImpl.java
  com.rush.logistic.client.slack/src/main/java/com/rush/logistic/client/slack/domain/service/SlackService.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/global/ApiResponse.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/global/JpaConfig.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/user/controller/UserController.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/user/dto/UserInfoResponseDto.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/user/repository/UserRepository.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/user/repository/UserRepositoryCustom.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/user/repository/UserRepositoryImpl.java
  com.rush.logistic.client.user-auth/src/main/java/com/rush/logistic/client/domain/user/service/UserService.java
Labels: refactor

#50 [Feat/redis cache] HUB 생성/조회/수정/삭제 Redis 캐싱메모리 적용
  com.rush.logistic.client.hub/build.gradle
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubRouteController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubInfoResponseDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/HubPointRequestDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubRouteMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/Hub.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/HubItem.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubItemRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubRouteService.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
  com.rush.logistic.client.hub/src/main/resources/application.yml
Labels: enhancement

#52 :sparkles: add: Access permission settings for each API
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubRouteController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/dto/UserDto.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/message/HubRouteMessage.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/BaseEntity.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/Hub.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/HubRoute.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/UserClient.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubRouteService.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#53 [feat/validation-auth] API별 HUB 관리자 접근권한 설정
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubRouteService.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#55 [Fix/company-product] 권한 등급에 따른 제약 버그 해결
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/company/service/CompanyService.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/product/controller/ProductController.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/domain/product/service/ProductService.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/client/ApiResponse.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/client/UserClient.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/client/UserResponseDto.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/client/UserRoleEnum.java
  com.rush.logistic.client.company-product/src/main/java/com/rush/logistic/client/company_product/global/exception/ErrorCode.java
Labels: bug, enhancement

#56 [feat/query-dsl] HUB, HUB route Query DSL 적용
  com.rush.logistic.client.hub/build.gradle
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/config/QueryDslConfig.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubRouteController.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/model/PagedModel.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRepositoryCustom.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRouteRepository.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/repository/HubRouteRepositoryCustom.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubRouteService.java
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/service/HubService.java
Labels: enhancement

#66 [Refactor/company-product] company-product DB, 주소 환경변수 처리
  com.rush.logistic.client.company-product/.gitignore
  com.rush.logistic.client.company-product/build.gradle
  com.rush.logistic.client.company-product/src/main/resources/application.yml
Labels: refactor

#67 [feat/hub-zipkin] HUB 서비스 Zipkin 적용
  com.rush.logistic.client.hub/build.gradle
  com.rush.logistic.client.hub/src/main/java/com/rush/logistic/client/hub/controller/HubController.java
  com.rush.logistic.client.hub/src/main/resources/application.yml
Labels: enhancement
